# Generated by Django 5.2.5 on 2026-02-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_project_source_code_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='drive_link',
            field=models.CharField(blank=True, help_text='Drive/public URL or static path, e.g. certificates/MyCert.pdf', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='demo_url',
            field=models.URLField(blank=True, help_text='Live link URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='highlights',
            field=models.JSONField(blank=True, default=list, help_text='JSON list, e.g. ["Responsive UI", "Fast load time"]'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_path',
            field=models.CharField(blank=True, help_text='Static path or full URL, e.g. images/projects/project.png', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.JSONField(blank=True, default=list, help_text='JSON list, e.g. ["Django", "HTML", "CSS"]'),
        ),
    ]
