"""
Django settings for myPortfolio_2025 project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from urllib.parse import urlparse, parse_qs

from dotenv import load_dotenv
from myApp import config as app_config
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = app_config.SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = app_config.DEBUG

# ALLOWED_HOSTS = app_config.ALLOWED_HOSTS
ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    # 'whitenoise.runserver_nonstatic',
    'myApp',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myPortfolio_2025.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR, "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myPortfolio_2025.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

def _build_database_config():
    database_url = app_config.DATABASE_URL.strip()
    if database_url:
        parsed = urlparse(database_url)
        if parsed.scheme.startswith("postgres"):
            db = {
                "ENGINE": "django.db.backends.postgresql",
                "NAME": parsed.path.lstrip("/"),
                "USER": parsed.username,
                "PASSWORD": parsed.password,
                "HOST": parsed.hostname,
                "PORT": parsed.port or "5432",
            }
            query = parse_qs(parsed.query or "")
            sslmode = (query.get("sslmode") or [""])[0]
            if sslmode:
                db["OPTIONS"] = {"sslmode": sslmode}
            return {"default": db}

    return {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


DATABASES = _build_database_config()


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# Where your static files are during development
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),  # e.g., /static/css/style.css
]

# Where Django will collect static files for production (e.g. Vercel)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files (uploaded images)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Email configuration (set these in environment variables)
EMAIL_BACKEND = app_config.EMAIL_BACKEND
EMAIL_HOST = app_config.EMAIL_HOST
EMAIL_PORT = app_config.EMAIL_PORT
EMAIL_HOST_USER = app_config.EMAIL_HOST_USER
EMAIL_HOST_PASSWORD = app_config.EMAIL_HOST_PASSWORD
EMAIL_USE_TLS = app_config.EMAIL_USE_TLS
EMAIL_USE_SSL = app_config.EMAIL_USE_SSL
DEFAULT_FROM_EMAIL = app_config.DEFAULT_FROM_EMAIL
PORTFOLIO_ADMIN_EMAIL = app_config.PORTFOLIO_ADMIN_EMAIL

# Optional branding for emails
SITE_URL = app_config.SITE_URL
EMAIL_LOGO_URL = app_config.EMAIL_LOGO_URL

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
